### ISSUE TITLE
Settings Don't Stick

### ISSUE THREAD

**Issue by redwolfe98** [nathan-osman/websocket-disabler#1]
when i use "websocket-disabler" to disable websockets, the setting doesn't stick when "firefox" is closed and then re-opened: after closing, and then re-opening "firefox", websockets are enabled, again..

also, i think it would be better if one could adjust the "disable websockets" / "enable websockets" settings from within firefox's "addons-manager", the same as you can with other addons..

**Comment by davidhedlund** [comment]
I agree, a **permanent** shift in the WebSocket setting should be implemented (as an additional option).

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by beerisgood** [comment]
Yes this would be nice, since its the task of this addon.

**Comment by beerisgood** [comment]
*push*

**Comment by beerisgood** [comment]
*push*

**Comment by nathan-osman** [comment]
I profusely apologize for the delay in getting this pushed. Anyway, it's fixed now and Firefox will remember that WebSockets are enabled / disabled between sessions. I'll be uploading this to AMO within the next few minutes.

**Comment by davidhedlund** [comment]
@nathan-osman Thank you.
