### ISSUE TITLE
Doesn't work with Pale Moon 27

### ISSUE THREAD

**Issue by beerisgood** [nathan-osman/websocket-disabler#2]
Can you please make a build for Pale Moon (27)?
http://www.palemoon.org/WIP/

That would be awesome!

**Comment by beerisgood** [comment]
*bump*
Can you please add Pale Moon support?

**Comment by nathan-osman** [comment]
I'll take a look at this. I don't _remember_ using any Australis-only features in the add-on, but if there are any, that would explain the incompatibility. I've installed Pale Moon to investigate further.

**Comment by nathan-osman** [comment]
Turned out to be an easy fix. To install the add-on, download [this](https://github.com/nathan-osman/websocket-disabler/archive/master.zip) file, rename the extension from `.zip` to `.xpi`, and then drag it into the Pale Moon window to install.

**Comment by beerisgood** [comment]
The install works, but if i test websocket support on that site: http://websocketstest.com i get that websocket is still activated.

**Comment by nathan-osman** [comment]
Did you go to Tools -> Web Developer -> Disable WebSockets?

**Comment by beerisgood** [comment]
That did the trick. Thanks!
Maybe this can be activated when the addon is activated? Since its the task of the addon.

**Edit:** It looks the setting is reset after a browser restart.

**Comment by beerisgood** [comment]
For guys with uBlock Origin:
Just add this as rule to block Websockets:
||ws://
||wss://
