### ISSUE TITLE
Compatibility with e10s missing

### ISSUE THREAD

**Issue by FibreFoX** [nathan-osman/websocket-disabler#3]
I'm using this Firefox with the new electrolysis feature enabled, but this addon is breaking that feature.

Would be nice to have this working with e10s.

**Comment by nathan-osman** [comment]
I wonder how disabling web sockets is affecting e10s. I'll have to take a deeper look at this and see if I can figure out what's going on.

**Comment by FibreFoX** [comment]
Wonderful :) it is indeed strange! I have installed [Add-on Compatibility Reporter](https://addons.mozilla.org/de/firefox/addon/add-on-compatibility-reporter/?src=api), it shows me that this plugin is not compatible ... haven't looked further into this.

**Comment by FibreFoX** [comment]
I don't know if you did something, but this seems not being e10s compatible, that reporter-plugin and `about:support` now shows me that multi-process is enabled with this plugin.

:) thanks for the nice plugin
